apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: omsorgsopptjening
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 2
    replication: 3
    retentionBytes: -1
    retentionHours: 672
    segmentHours: 672
  acl:
    - team: pensjonopptjening
      application: omsorgsopptjening-start-innlesning
      access: write
    - team: pensjonopptjening
      application: omsorgsopptjening-bestem-pensjonsopptjening
      access: read