name: Deploy omsorgsopptjening-topic to prod-gcp

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nais/prod-gcp.yaml'
jobs:
  deploy:
    name: 'Deploy omsorgsopptjening-topic to prod-gcp'
    permissions:
      contents: "read"
      id-token: "write"  
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Deploy resources to prod-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-gcp.yaml
